
-- actions

CREATE TABLE IF NOT EXISTS actionstypes (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	code VARCHAR(20) NOT NULL,
	name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS actions (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	id_type INTEGER NOT NULL,
	name VARCHAR(100) NOT NULL,
	params VARCHAR(250) NOT NULL,
	FOREIGN KEY(id_type) REFERENCES actionstypes(id) ON DELETE CASCADE ON UPDATE CASCADE
);
