
-- triggers

CREATE TABLE IF NOT EXISTS triggers (

	id INTEGER PRIMARY KEY AUTOINCREMENT,

	code VARCHAR(20) NOT NULL,
	name VARCHAR(100) NOT NULL

);

-- actions

CREATE TABLE IF NOT EXISTS actionstypes (

	id INTEGER PRIMARY KEY AUTOINCREMENT,

	code VARCHAR(20) UNIQUE NOT NULL,
	name VARCHAR(100) NOT NULL

);

CREATE TABLE IF NOT EXISTS actions (

	id INTEGER PRIMARY KEY AUTOINCREMENT,

	id_after_cond INTEGER DEFAULT NULL,
	id_type INTEGER NOT NULL,

	name VARCHAR(100) NOT NULL,
	params VARCHAR(250) NOT NULL,

	FOREIGN KEY (id_after_cond) REFERENCES conditions(id) ON DELETE SET NULL ON UPDATE CASCADE,
	FOREIGN KEY (id_type) REFERENCES actionstypes(id) ON DELETE CASCADE ON UPDATE CASCADE

);

-- conditions

CREATE TABLE IF NOT EXISTS conditionstypes (

	id INTEGER PRIMARY KEY AUTOINCREMENT,

	code VARCHAR(20) UNIQUE NOT NULL,
	name VARCHAR(100) NOT NULL

);

CREATE TABLE IF NOT EXISTS conditions (

	id INTEGER PRIMARY KEY AUTOINCREMENT,

	name VARCHAR(100) NOT NULL,

	id_onyes_cond INTEGER DEFAULT NULL,
	id_onno_cond INTEGER DEFAULT NULL,
	id_onyes_act INTEGER DEFAULT NULL,
	id_onno_act INTEGER DEFAULT NULL,
	id_type INTEGER NOT NULL,

	datavalue VARCHAR(100) NOT NULL,
	dataname VARCHAR(100) NOT NULL,

	FOREIGN KEY (id_onyes_cond) REFERENCES conditions(id) ON DELETE SET NULL ON UPDATE CASCADE,
	FOREIGN KEY (id_onno_cond) REFERENCES conditions(id) ON DELETE SET NULL ON UPDATE CASCADE,
	FOREIGN KEY (id_onyes_act) REFERENCES actions(id) ON DELETE SET NULL ON UPDATE CASCADE,
	FOREIGN KEY (id_onno_act) REFERENCES actions(id) ON DELETE SET NULL ON UPDATE CASCADE,
	FOREIGN KEY (id_type) REFERENCES conditionstypes(id) ON DELETE CASCADE ON UPDATE CASCADE

);

-- scenarios

CREATE TABLE IF NOT EXISTS scenarios (

	id INTEGER PRIMARY KEY AUTOINCREMENT,

	id_start_cond INTEGER DEFAULT NULL,

	name VARCHAR(100) NOT NULL,
	active INT(1) NOT NULL DEFAULT 0,

	FOREIGN KEY (id_start_cond) REFERENCES conditions(id) ON DELETE SET NULL ON UPDATE CASCADE

);
