
-- scenarios

CREATE TABLE IF NOT EXISTS scenarios (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	name VARCHAR(100) NOT NULL
);

-- triggers

CREATE TABLE IF NOT EXISTS triggerstypes (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	code VARCHAR(20) UNIQUE NOT NULL,
	name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS triggers (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	id_type INTEGER NOT NULL,
	name VARCHAR(100) NOT NULL,
	FOREIGN KEY(id_type) REFERENCES triggerstypes(id) ON DELETE CASCADE ON UPDATE CASCADE
);

-- actions

CREATE TABLE IF NOT EXISTS actionstypes (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	code VARCHAR(20) UNIQUE NOT NULL,
	name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS actions (
	id INTEGER PRIMARY KEY AUTOINCREMENT,
	id_type INTEGER NOT NULL,
	name VARCHAR(100) NOT NULL,
	params VARCHAR(250) NOT NULL,
	FOREIGN KEY(id_type) REFERENCES actionstypes(id) ON DELETE CASCADE ON UPDATE CASCADE
);
